name: Events demo
on: [push]
jobs: 
    deploy: 
        runs-on: ubuntu-latest
        steps:
            - name: get code 
              uses: actions/checkout@v3
            - name: Install dependenices
              uses: npm ci